version: '3'

services:
  api:
    build: ./api
    image: time_manager_api
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  front:
    build: ./front
    image: time_manager_front
    restart: always
    depends_on:
      - api
    ports:
      - "8080:8080"

  mongo:
    container_name: time_manager_mongo
    image: "mongo"
    #command: --auth
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/var/lib/mongodb_timemanager/data

volumes:
  db-data:
